# Site settings
title:    Blog title
baseurl: "http://your-github-repo.github.io"

description: > #
 You can add a description to this section to explain the blog or your self.

site_owner: Your Name
site_strapline: a cool strap line for the site
site_owner_email:    youremail@domain.com
url: "http://your-github-repo.github.io" # the base hostname & protocol for your site


# Social media details
twitter_username: twitter_handle
github_username:  github_handle


# Build settings
markdown: kramdown

permalink:  /blog/:title/
paginate:   4

excerpt_separator: <!-- more -->

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"
      author: "Your Name"

exclude: ['LICENSE.md','README.md','GemFile','Gemfile.lock',
          'package.json', 'bower.json','gulpfile.js',
          'node_modules','_bower_components']

sass:
  sass_dir: _scss
  compressed: true
